version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  ws-server-1:
    build: ./server
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - SERVER=ws-server-1
    ports:
      - "3000:3000"
    depends_on:
      - redis

  ws-server-2:
    build: ./server
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - SERVER=ws-server-2
    ports:
      - "3001:3001"
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ws-server-1
      - ws-server-2