version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  server:
    build: ./server
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - redis
